include: "https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml"

stages:
    - test
    - cross_environment

flatpak:
    stage: test
    variables:
        MANIFEST_PATH: "build-aux/flatpak/org.gnome.Characters.json"
        FLATPAK_MODULE: "gnome-characters"
        APP_ID: "org.gnome.CharactersDevel"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        BUNDLE: "gnome-characters.flatpak"
    extends: .flatpak

nightly:
    extends: ".publish_nightly"
    stage: cross_environment
    dependencies: ["flatpak"]

eslint:
  image: registry.gitlab.gnome.org/gnome/gnome-shell/fedora/36:2022-07-06.0

  variables:
    LINT_LOG: "eslint-report.txt"
  script:
    - eslint -o $LINT_LOG --no-color src || { cat $LINT_LOG; false; }
  artifacts:
    paths:
      - ${LINT_LOG}
    when: on_failure

