name: gnome-characters
version: git
adopt-info: gnome-characters
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

layout:
  /usr/bin/gjs:
    symlink: $SNAP/gnome-platform/usr/bin/gjs

slots:
  # for GtkApplication registration
  gnome-characters:
    interface: dbus
    bus: session
    name: org.gnome.Characters

apps:
  gnome-characters:
    command: usr/share/org.gnome.Characters/org.gnome.Characters
    extensions: [gnome-3-28]
    plugs:
      - browser-support
      - gsettings
      - home
    desktop: usr/share/applications/org.gnome.Characters.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/org.gnome.Characters:$SNAP/gnome-platform/usr/lib/
      GI_TYPELIB_PATH: $SNAP/gnome-platform/usr/lib/gjs/girepository-1.0

parts:
  gnome-characters:
    source-type: git
    source: .
    plugin: meson
    meson-parameters: [--buildtype=release, --prefix=/snap/gnome-characters/current/usr]
    parse-info: [usr/share/metainfo/org.gnome.Characters.appdata.xml]
    organize:
      snap/gnome-characters/current/usr: usr
    override-pull: |
      snapcraftctl pull
      sed -i.bak -e 's|=@appid@$|=${SNAP}/meta/gui/org.gnome.Characters.svg|g' data/org.gnome.Characters.desktop.in
      sed -i.bak -e 's|=@bindir@/gnome-characters$|=${SNAP}/usr/share/org.gnome.Characters/org.gnome.Characters|g' data/org.gnome.Characters.desktop.in
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/scalable/apps/org.gnome.Characters.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
      rm -f $SNAPCRAFT_PART_INSTALL/snap/gnome-characters/current/usr/bin/gnome-characters
    build-packages:
      - desktop-file-utils
      - gettext
      - gsettings-desktop-schemas-dev
      - itstool
      - appstream-util
      - libglib2.0-dev
      - libgtk-3-dev
      - libgirepository1.0-dev
      - libgjs-dev
      - gjs
      - gperf
      - libgdk-pixbuf2.0-dev
      - libpango1.0-dev
      - libunistring-dev

  libraries:
    plugin: nil
    stage-packages:
      - libreadline5
      - libunistring2
    prime:
      - "usr/lib/*/libmozjs*"
      - "usr/lib/*.*"
      - "lib/*/libreadline.so*"
      - "usr/lib/*/libunistring.so*"
