name: gnome-characters
version: git
summary: A character map application
description: |
  Characters is a simple utility application to find and
  insert unusual characters.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

plugs:
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604:gnome-3-26-1604

slots:
  # for GtkApplication registration
  gnome-characters:
    interface: dbus
    bus: session
    name: org.gnome.Characters

apps:
  gnome-characters:
    command: desktop-launch gnome-characters
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - unity7
      - wayland
    desktop: usr/share/applications/org.gnome.Characters.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/gnome-characters

parts:
  iso-codes:
    after: [desktop-gnome-platform]
    source: https://pkg-isocodes.alioth.debian.org/downloads/iso-codes-3.75.tar.xz
    plugin: autotools
    # workaround the issue described in https://launchpad.net/bugs/1583250
    configflags: [--prefix=/snap/gnome-characters/current/usr]
    organize:
      snap/gnome-characters/current/usr: usr
    build-attributes: ['no-system-libraries']
    build-packages:
      - gettext
      - python3
  gnome-desktop:
    after: [iso-codes]
    source: https://git.gnome.org/browse/gnome-desktop
    source-type: git
    source-tag: 3.26.0
    plugin: autotools
    prepare:
      sed -i.bak -e 's|.*ISO_CODES_PREFIX=.*|ISO_CODES_PREFIX=/snap/gnome-characters/current/usr|g' configure.ac
    # workaround the issue described in https://launchpad.net/bugs/1583250
    configflags: [--prefix=/snap/gnome-characters/current/usr, --disable-date-in-gnome-version, --with-gnome-distributor=Ubuntu]
    organize:
      snap/gnome-characters/current/usr: usr
    build-attributes: ['no-system-libraries']
    build-packages:
      - libglib2.0-dev
      - gnome-common
      - intltool
      - gnome-pkg-tools
      - gtk-doc-tools
      - docbook-xml
      - libx11-dev
      - xkb-data
      - libgdk-pixbuf2.0-dev
      - libgl1-mesa-dev
      - libgtk-3-dev
      - libxml2-dev
      - libglib2.0-doc
      - libgtk-3-doc
      - libseccomp-dev
      - libudev-dev
      - gobject-introspection
      - libgirepository1.0-dev
      - gsettings-desktop-schemas-dev
      - yelp-tools
  gnome-characters:
    after: [gnome-desktop]
    source: .
    source-type: git
    plugin: autotools
    configflags: [--prefix=/snap/gnome-characters/current/usr]
    organize:
      snap/gnome-characters/current/usr: usr
    prepare: |
      sed -i.bak -e 's|=gnome-characters$|=${SNAP}/meta/gui/gnome-characters.png|g' data/org.gnome.Characters.desktop.in
      sed -i.bak -e 's|@GJS@|/snap/gnome-characters/current/usr/bin/gjs|g' src/org.gnome.Characters.in
      sed -i.bak -e 's|@GJS@|/snap/gnome-characters/current/usr/bin/gjs|g' src/org.gnome.Characters.BackgroundService.in
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/256x256/apps/gnome-characters.png $SNAPCRAFT_PART_INSTALL/meta/gui/
    build-attributes: ['no-system-libraries']
    build-packages:
      - desktop-file-utils
      - gettext
      - gnome-common
      - gsettings-desktop-schemas-dev
      - intltool
      - appstream-util
      - gnome-pkg-tools
      - pkg-config
      - libglib2.0-dev
      - libgtk-3-dev
      - libgirepository1.0-dev
      - libgjs-dev
      - gjs
      - gperf
      - libgdk-pixbuf2.0-dev
      - libpango1.0-dev

  libraries:
    plugin: nil
    stage-packages:
      - gjs
      - gir1.2-gdkpixbuf-2.0
      - gir1.2-glib-2.0
      - gir1.2-gtk-3.0
      - gir1.2-gnomedesktop-3.0
    prime:
      - "usr/bin/gjs*"
      - "usr/lib/*/girepository-1.0*"
      - "usr/lib/*/libmozjs*"
      - "usr/lib/*.*"
